/**
 * License Token Validation for Cloudflare Worker
 *
 * Validates Ed25519-signed offline license tokens (hxs_lic_...)
 * These tokens are generated by the admin script and allow offline usage
 * of the Hexis engine and cloud triage services.
 */

import { Env } from '../index';

interface LicensePayload {
    license_id: string;
    customer_id: string;
    expires_at: number | null;
    features: string[];
    issued_at: number;
    version: string;
}

interface ValidationResult {
    valid: boolean;
    customerId?: string;
    features?: string[];
    error?: string;
}

/**
 * Get the Ed25519 public key for license validation
 * In production, this should be stored in Cloudflare KV or Workers Secrets
 */
async function getPublicKey(env: Env): Promise<CryptoKey | null> {
    // Try to get from KV storage first
    try {
        const publicKeyPem = await env.LICENSE_PUBLIC_KEY?.get('hexis-public-key');
        if (publicKeyPem) {
            return await crypto.subtle.importKey(
                'spki',
                base64ToArrayBuffer(publicKeyPem),
                { name: 'Ed25519' },
                false,
                ['verify']
            );
        }
    } catch (e) {
        console.warn('Failed to load public key from KV:', e);
    }

    // Fallback: use hardcoded public key (for development/testing)
    // In production, this should be configured via Workers Secrets
    const hardcodedPublicKeyPem = env.HEXIS_PUBLIC_KEY;
    if (hardcodedPublicKeyPem) {
        try {
            return await crypto.subtle.importKey(
                'spki',
                base64ToArrayBuffer(hardcodedPublicKeyPem),
                { name: 'Ed25519' },
                false,
                ['verify']
            );
        } catch (e) {
            console.warn('Failed to import hardcoded public key:', e);
        }
    }

    return null;
}

/**
 * Convert base64 string to ArrayBuffer
 */
function base64ToArrayBuffer(base64: string): ArrayBuffer {
    const binaryString = atob(base64);
    const bytes = new Uint8Array(binaryString.length);
    for (let i = 0; i < binaryString.length; i++) {
        bytes[i] = binaryString.charCodeAt(i);
    }
    // Slice the buffer to get a clean ArrayBuffer without Uint8Array prototype
    return bytes.buffer.slice(0);
}

/**
 * Convert base64url string to ArrayBuffer
 */
function base64urlToArrayBuffer(base64url: string): ArrayBuffer {
    // Convert base64url to base64
    const base64 = base64url.replace(/-/g, '+').replace(/_/g, '/');
    const paddingLength = (4 - (base64.length % 4)) % 4;
    const paddedBase64 = base64 + '='.repeat(paddingLength);
    return base64ToArrayBuffer(paddedBase64);
}

/**
 * Validate an Ed25519-signed license token
 */
export async function validateLicenseToken(token: string, env: Env): Promise<ValidationResult> {
    if (!token.startsWith('hxs_lic_')) {
        return { valid: false, error: 'Invalid token format: must start with hxs_lic_' };
    }

    const parts = token.split('.');
    if (parts.length !== 3) {
        return { valid: false, error: 'Invalid token format: expected 3 parts' };
    }

    const payloadBase64Url = parts[1];
    const signatureBase64Url = parts[2];

    try {
        // Get the public key for validation
        const publicKey = await getPublicKey(env);
        if (!publicKey) {
            return { valid: false, error: 'Public key not configured' };
        }

        // Decode payload and signature
        const payloadBuffer = base64urlToArrayBuffer(payloadBase64Url);
        const signatureBuffer = base64urlToArrayBuffer(signatureBase64Url);

        // Verify the signature
        const isValid = await crypto.subtle.verify(
            { name: 'Ed25519' },
            publicKey,
            signatureBuffer,
            payloadBuffer
        );

        if (!isValid) {
            return { valid: false, error: 'Invalid signature' };
        }

        // Parse the payload
        const payloadJson = new TextDecoder().decode(payloadBuffer);
        const payload: LicensePayload = JSON.parse(payloadJson);

        // Check expiration
        if (payload.expires_at !== null) {
            const now = Math.floor(Date.now() / 1000);
            if (payload.expires_at < now) {
                return { valid: false, error: 'License token has expired' };
            }
        }

        // Check version
        if (payload.version !== '1.0.0') {
            return { valid: false, error: 'Unsupported license token version' };
        }

        return {
            valid: true,
            customerId: payload.customer_id,
            features: payload.features,
        };

    } catch (error) {
        console.error('License validation error:', error);
        return { valid: false, error: `Validation failed: ${error}` };
    }
}

/**
 * Store the public key in KV (for admin use)
 */
export async function storePublicKey(env: Env, publicKeyPem: string): Promise<boolean> {
    try {
        await env.LICENSE_PUBLIC_KEY?.put('hexis-public-key', publicKeyPem);
        return true;
    } catch (e) {
        console.error('Failed to store public key:', e);
        return false;
    }
}

/**
 * Generate a sample license token for testing (self-contained)
 * This is for development/testing purposes only
 */
export async function generateTestLicenseToken(customerId: string): Promise<string> {
    // Generate a test keypair
    const keyPair = await crypto.subtle.generateKey(
        { name: 'Ed25519' },
        true,
        ['sign', 'verify']
    );

    // Create payload
    const payload: LicensePayload = {
        license_id: `lic_test_${crypto.randomUUID().replace(/-/g, '')}`,
        customer_id: customerId,
        expires_at: null, // Never expires for test
        features: ['static_analysis', 'ai_triage', 'ci_cd'],
        issued_at: Math.floor(Date.now() / 1000),
        version: '1.0.0',
    };

    const payloadJson = JSON.stringify(payload);
    const payloadBuffer = new TextEncoder().encode(payloadJson);

    // Sign the payload
    const signatureBuffer = await crypto.subtle.sign(
        { name: 'Ed25519' },
        keyPair.privateKey,
        payloadBuffer
    );

    // Export public key for storage
    const publicKeyBuffer = await crypto.subtle.exportKey('spki', keyPair.publicKey);
    const publicKeyPem = arrayBufferToBase64(publicKeyBuffer);

    // Convert buffers to base64url
    const payloadBase64Url = arrayBufferToBase64Url(payloadBuffer.buffer);
    const signatureBase64Url = arrayBufferToBase64Url(signatureBuffer);

    const token = `hxs_lic_${payloadBase64Url}.${signatureBase64Url}`;

    console.log('Test License Token:', token);
    console.log('Public Key (store in HEXIS_PUBLIC_KEY):', publicKeyPem);

    return token;
}

/**
 * Convert ArrayBuffer to base64
 */
function arrayBufferToBase64(buffer: ArrayBuffer): string {
    const bytes = new Uint8Array(buffer);
    return btoa(String.fromCharCode(...Array.from(bytes)));
}

/**
 * Convert ArrayBuffer to base64url
 */
function arrayBufferToBase64Url(buffer: ArrayBuffer): string {
    const bytes = new Uint8Array(buffer);
    const base64 = btoa(String.fromCharCode(...Array.from(bytes)));
    return base64.replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
}
