//! Continuous Relaxation Compiler
//!
//! This module takes parsed `BinaryMetadata` and emits a standalone WGSL compute shader.
//! The shader describes a smooth (sigmoid-based) penalty manifold over an input payload.

use crate::loader::BinaryMetadata;

/// Generates a complete WGSL compute shader.
///
/// ## Shader Contract
/// - `@group(0) @binding(0)`: uniform buffer containing `PAYLOAD_LEN` floats.
///   These represent the user's input payload bytes as `f32` values (typically 0..255).
/// - `@group(0) @binding(1)`: storage buffer with a single `f32` penalty output.
///
/// The shader computes a cumulative penalty score. When all constraints match exactly,
/// the score reaches `0.0`.
pub fn compile_wgsl(metadata: &BinaryMetadata) -> String {
    // Sanity guard: if metadata looks degenerate, return a shader anyway (always valid WGSL)
    // but keep payload size minimal.
    // Keep the generated shader deterministic given the same metadata.
    // We generate one constraint per discovered “section”, plus a few global constraints.
    let payload_len: usize = (8 + metadata.num_sections).clamp(1, 4096);

    // Build a simple deterministic seed from the metadata fields.
    let mut seed: u32 = 2166136261; // FNV-1a offset basis
    seed = fnv1a_u32(seed, metadata.file_type.as_bytes());
    seed = fnv1a_u32(seed, metadata.architecture.as_bytes());
    seed = seed.wrapping_mul(16777619) ^ (metadata.entry_point as u32);
    seed = seed.wrapping_mul(16777619) ^ (metadata.num_sections as u32);

    let mut wgsl = String::new();

    // Header + bindings
    wgsl.push_str(&format!(
        "// Auto-generated by native_core::relaxer\n\nconst PAYLOAD_LEN: u32 = {payload_len}u;\n\n"
    ));
    wgsl.push_str(
        "struct InputPayload {\n  bytes: array<f32, PAYLOAD_LEN>,\n};\n\n",
    );
    wgsl.push_str(
        "struct Output {\n  penalty: f32,\n};\n\n",
    );
    wgsl.push_str(
        "@group(0) @binding(0) var<uniform> input_payload: InputPayload;\n",
    );
    wgsl.push_str(
        "@group(0) @binding(1) var<storage, read_write> output: Output;\n\n",
    );

    // Helpers
    wgsl.push_str(
        "fn sigmoid(input_val: f32, target_val: f32, w: f32) -> f32 {\n  // 1 / (1 + exp(-w * (x - t)))\n  return 1.0 / (1.0 + exp(-w * (input_val - target_val)));\n}\n\n",
    );
    wgsl.push_str(
        "fn penalty_eq_sigmoid(input_val: f32, target_val: f32, w: f32) -> f32 {\n  // When input == target => sigmoid == 0.5 => penalty 0\n  let s = sigmoid(input_val, target_val, w);\n  let d = (s - 0.5);\n  return (d * d) * 4.0;\n}\n\n",
    );

    // Entry point
    // NOTE: workgroup size 1 for determinism; caller can dispatch 1.
    wgsl.push_str("@compute @workgroup_size(1)\nfn main() {\n");
    wgsl.push_str("  var score: f32 = 0.0;\n");
    wgsl.push_str("  let w: f32 = 12.0;\n\n");

    // Global constraints derived from the metadata
    // 0: file_type length
    wgsl.push_str(&format!(
        "  // Constraint: file_type length\n  score = score + penalty_eq_sigmoid(input_payload.bytes[0], {target} , w);\n\n",
        target = metadata.file_type.len() as f32
    ));
    // 1: architecture length
    wgsl.push_str(&format!(
        "  // Constraint: architecture length\n  score = score + penalty_eq_sigmoid(input_payload.bytes[1], {target} , w);\n\n",
        target = metadata.architecture.len() as f32
    ));
    // 2..5: entry point low 4 bytes
    let ep = metadata.entry_point as u32;
    for (i, b) in ep.to_le_bytes().iter().enumerate() {
        wgsl.push_str(&format!(
            "  // Constraint: entry_point byte {i}\n  score = score + penalty_eq_sigmoid(input_payload.bytes[{idx}], {target}, w);\n\n",
            i = i,
            idx = 2 + i,
            target = *b as f32
        ));
    }
    // 6: num_sections
    wgsl.push_str(&format!(
        "  // Constraint: number of sections\n  score = score + penalty_eq_sigmoid(input_payload.bytes[6], {target}, w);\n\n",
        target = metadata.num_sections as f32
    ));

    // Section-derived constraints
    // Each discovered “section” i maps to a deterministic target byte value.
    for i in 0..metadata.num_sections {
        // Avoid out-of-bounds vs PAYLOAD_LEN.
        let idx = 7 + i;
        if idx >= payload_len {
            break;
        }
        let t = target_for_section(seed, i) as f32;
        wgsl.push_str(&format!(
            "  // Constraint: section_{i}\n  score = score + penalty_eq_sigmoid(input_payload.bytes[{idx}], {target}, w);\n\n",
            i = i,
            idx = idx,
            target = t
        ));
    }

    wgsl.push_str("  output.penalty = score;\n");
    wgsl.push_str("}\n");

    wgsl
}

fn fnv1a_u32(mut hash: u32, bytes: &[u8]) -> u32 {
    for &b in bytes {
        hash ^= b as u32;
        hash = hash.wrapping_mul(16777619);
    }
    hash
}

fn target_for_section(seed: u32, i: usize) -> u8 {
    // A tiny deterministic mixer; not cryptographic.
    let mut x = seed ^ (i as u32).wrapping_mul(0x9E3779B9);
    x ^= x >> 16;
    x = x.wrapping_mul(0x7FEB352D);
    x ^= x >> 15;
    x = x.wrapping_mul(0x846CA68B);
    x ^= x >> 16;
    (x & 0xFF) as u8
}
