name = "patcher"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = [ "nodejs_compat" ]
account_id = "7367c028857d9916fee45e693edbe17f"

# 1. Force minification to drastically reduce bundle size (Placed at top level)
minify = true

[vars]
# 2. Don't forget your auth base URL!


APP_URL = "https://patcher.ericijeoma7767.workers.dev"
PAYSTACK_PUBLIC_KEY = "pk_test_YOUR_PAYSTACK_PUBLIC_KEY"

[[ratelimits]]
name = "RATE_LIMITER"
namespace_id = "1001"
simple = { limit = 10, period = 60 }

[[kv_namespaces]]
binding = "AUTH_KV"
id = "8dea59dec76343849d9d39570ae86f71"

[build]
command = "node scripts/copy-engine-assets.js && pnpm run build"

[observability]
enabled = true

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "hexis-db"
database_id = "2efbd344-6b80-4933-86af-87dd49ed9bf5"

# 3. Rule Block 1: Handle standard JavaScript modules
[[rules]]
type = "ESModule"
globs = ["**/*.js", "**/*.mjs"]
fallthrough = true

# 4. Rule Block 2: Tell Wrangler to treat WASM as native binaries, not huge strings
[[rules]]
type = "CompiledWasm"
globs = ["**/*.wasm"]
fallthrough = true


[[rules]]
type = "Text"
globs = ["**/*.css"]
fallthrough = true
